# Generated by Django 6.0 on 2025-12-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=30)),
                ('Transactiontype', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=7)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Date', models.DateField()),
                ('Categorychoice', models.CharField(choices=[('Salary', 'Salary'), ('Gift', 'Gift'), ('Earnings', 'Earnings'), ('Food', 'Food'), ('Rent', 'Rent'), ('Personal', 'Personal'), ('Investment', 'Investment'), ('Savings', 'Savings')], max_length=20)),
                ('Description', models.CharField(blank=True, max_length=40)),
            ],
        ),
    ]
